In [8]:
# importing numpy
import numpy as np

In [1]:
# list
lis_1=[1,2,3,4,5]

In [4]:
# array.
arr_1=np.array(lis_1)
print(arr_1)

[1 2 3 4 5]


In [6]:
lis_2=[range(1,5), range(5,9)]
arr_2=np.array(lis_2)
print(arr_2)

[[1 2 3 4]
 [5 6 7 8]]


In [7]:
# tolist command convert array back to list
arr_2.tolist()

[[1, 2, 3, 4], [5, 6, 7, 8]]

In [9]:
# creating 1D zeros array
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [11]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [12]:
# creating 1D ones array
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [14]:
# numpy.linspace works in the following way
#numpy.linspace(start, stop, num, endpoint=True, retstep=False, dtype=None, axis=0)[source]
np.linspace(0,1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [15]:
# work same as linspace.Return numbers spaced evenly on a log scale.
#In linear space, the sequence starts at base ** start (base to the power of start) and ends with base ** stop
np.logspace(0,3,4)

array([   1.,   10.,  100., 1000.])

In [18]:
array_3= np.arange(5)
print(array_3)
#The np.arange function produced a sequence of 5 evenly spaced values from 0 to 4, stored as an ndarray object

[0 1 2 3 4]


In [20]:
# converting integer array in to floating list using (astype)syntex
array_float= array_3.astype(float)
print(array_float)

[0. 1. 2. 3. 4.]


# Examin array

In [23]:
arr_1.dtype # datatype

dtype('int32')

In [24]:
arr_2.dtype # datatype

dtype('int32')

In [26]:
print(arr_2.ndim) # dimensional

2


In [27]:
arr_2.shape # 2 rows and 4 columns

(2, 4)

In [28]:
arr_2.size # total elements 

8

In [29]:
len(arr_2) # it shows the rows of the array

2

# Reshaping

In [31]:
arr_4= np.arange(10, dtype=float)
print(arr_4)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [33]:
arr_4reshape=arr_4.reshape((2,5))
print(arr_4reshape)

[[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]]


In [35]:
print(arr_4reshape.shape)

(2, 5)


In [36]:
print(arr_4reshape.reshape(5,2))

[[0. 1.]
 [2. 3.]
 [4. 5.]
 [6. 7.]
 [8. 9.]]


In [38]:
a_mat= np.array([0,1])
print(a_mat)

[0 1]


In [39]:
a_mat_col= a_mat[:, np.newaxis] 
print(a_mat_col)
#the newaxis expression is used to increase the dimension of the existing array by one more dimension.
# like 1D to 2D, 2D to 3D.....

[[0]
 [1]]


In [43]:
a_mat_col_or= a_mat[:,None]
print(a_mat_col_or)
print(a_mat_col_or.T) # transpose the matrix

[[0]
 [1]]
[[0 1]]


# Flatten

In [50]:
arr_4reshape

array([[0., 1., 2., 3., 4.],
       [5., 6., 7., 8., 9.]])

In [48]:
arr_flt= arr_4reshape.flatten()
print(arr_flt)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [49]:
arr_flt[0]=33
print(arr_flt)

[33.  1.  2.  3.  4.  5.  6.  7.  8.  9.]


# Stack arrays

In [53]:
a= np.array([0,1])
b=np.array([2,3])

In [55]:
print(a)
print(b)

[0 1]
[2 3]


In [57]:
ab= np.stack((a,b))
print(ab)

[[0 1]
 [2 3]]


In [59]:
ab_T=ab.T
print(ab_T)

[[0 2]
 [1 3]]


In [60]:
# another way. hstack expression transpose the matrix
np.hstack((a[:,None], b[:,None]))

array([[0, 2],
       [1, 3]])

# Selection

In [61]:
arr_4reshape

array([[0., 1., 2., 3., 4.],
       [5., 6., 7., 8., 9.]])

In [62]:
arr_4reshape[0]

array([0., 1., 2., 3., 4.])

In [63]:
arr_4reshape[0,3] # row 0, column 3

3.0

# Slicing

In [65]:
arr_4reshape[0,:]

array([0., 1., 2., 3., 4.])

In [66]:
arr_4reshape[:,0]

array([0., 5.])

In [67]:
arr_4reshape[:, :2]

array([[0., 1.],
       [5., 6.]])

In [68]:
arr_4reshape[:, 2:]

array([[2., 3., 4.],
       [7., 8., 9.]])

In [69]:
arr_4_re_2= arr_4reshape[:,1:4]
print(arr_4_re_2)

[[1. 2. 3.]
 [6. 7. 8.]]


In [70]:
arr_4_re_2[0,0]=33
print(arr_4_re_2)

[[33.  2.  3.]
 [ 6.  7.  8.]]


In [71]:
print(arr_4reshape[0,::-1])

[ 4.  3.  2. 33.  0.]


In [72]:
# Integer or boolean array indexing
arr_I= arr_4reshape[:, [1,2,3]]
print(arr_I)

[[33.  2.  3.]
 [ 6.  7.  8.]]


In [74]:
arr_I[0,0]= 44
print(arr_I)

[[44.  2.  3.]
 [ 6.  7.  8.]]


In [76]:
arr_I = arr_4reshape[arr_4reshape>5]
print(arr_I)

[33.  6.  7.  8.  9.]


In [77]:
arr_I[0]=44
print(arr_I)

[44.  6.  7.  8.  9.]


In [78]:
arr_4reshape[arr_4reshape>5]=0
print(arr_4reshape)

[[0. 0. 2. 3. 4.]
 [5. 0. 0. 0. 0.]]


In [80]:
# Boolean array indexing
var= np.array(['bob','joe','will','bob'])
print(var)

['bob' 'joe' 'will' 'bob']


In [81]:
var=='bob'

array([ True, False, False,  True])

In [82]:
var[var !='bob'] # != indicates not equal 

array(['joe', 'will'], dtype='<U4')

In [91]:
(var=='bob')|(var=='will')

array([ True, False, False,  True])

In [88]:
var[var != 'bob']= 'joe'

In [89]:
print(var)

['bob' 'joe' 'joe' 'bob']


In [90]:
np.unique(var)

array(['bob', 'joe'], dtype='<U4')

# Vectorized operations

In [93]:
num= np.arange(5)
num*10
num= np.sqrt(num)
print(num)

[0.         1.         1.41421356 1.73205081 2.        ]


In [94]:
np.ceil(num) # ceil expression is used for round the nearest numbers

array([0., 1., 2., 2., 2.])

In [96]:
np.isnan(num) # checking the missing value

array([False, False, False, False, False])

In [97]:
num + np.arange(5)

array([0.        , 2.        , 3.41421356, 4.73205081, 6.        ])

In [99]:
np.maximum(num, np.array([1,-2,-3,-4,5])) # taking the maximum element comparing two arrays. Broadcasting

array([1.        , 1.        , 1.41421356, 1.73205081, 5.        ])

In [105]:
# Compute Euclidean distance between 2 vectors
vec_1= np.random.randn(10)
vec_2= np.random.randn(10)
distance= np.sqrt(np.sum(vec_1-vec_2)**2)

In [106]:
distance

3.6063288756831513

In [108]:
rand_1= np.random.randn(4,2)
rand_1

array([[ 0.49195437,  1.12663721],
       [ 0.46175921,  1.02869024],
       [-0.38401206, -0.73170968],
       [ 0.01320743,  0.59855511]])

In [114]:
rand_1.mean()

0.32563522949312823

In [115]:
rand_1.std()

0.6098930489458713

In [116]:
rand_1.argmin() # index of minmum element

5

In [117]:
rand_1.sum()

2.605081835945026

In [118]:
rand_1.sum(axis=0) # sum of columns

array([0.58290895, 2.02217288])

In [119]:
rand_1.sum(axis=1) # sum of rows

array([ 1.61859158,  1.49044945, -1.11572174,  0.61176254])

In [120]:
(rand_1>0).sum()

6

In [121]:
(rand_1>0).any()

True

In [123]:
(rand_1>0).all()

False

In [128]:
# randon munbers
rand_2=np.random.seed(122234)

In [129]:
np.random.rand(2,3)

array([[0.40965668, 0.54794589, 0.81769839],
       [0.87962455, 0.22254637, 0.66931799]])

In [130]:
np.random.randn(10)

array([-0.22184736, -1.06194637, -1.47016842, -0.03173999,  0.70701545,
        0.63767395, -0.0028019 , -0.86145445, -0.61182069,  1.1064933 ])

In [132]:
np.random.randint(0,2,10)

array([0, 0, 1, 0, 0, 1, 0, 0, 0, 1])

# Broadcasting

In [133]:
c= np.array([[0,0,0],
            [10,10,10],
            [20,20,20],
            [30,30,30]])
d = np.array([0,1,2])
print(c+d)

[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]


# Exercise

In [135]:
X_1= np.random.randn(4,2)
X_1

array([[-0.49155682, -1.0708475 ],
       [-0.24658117, -1.8353131 ],
       [ 0.51714858, -1.17946306],
       [ 0.42862081, -2.17913076]])

In [148]:
np.amin(X_1, axis=0)

array([-0.49155682, -2.17913076])

In [163]:
def std(X_1):
    norm_X_1=(X_1-np.mean(X_1))/np.std(X_1)
    return norm_X_1

In [164]:
std(X_1)

array([[ 0.28759402, -0.33970587],
       [ 0.55287223, -1.1675272 ],
       [ 1.37989673, -0.45732303],
       [ 1.28403215, -1.53983903]])

In [167]:
from sklearn.preprocessing import StandardScaler
standardized_data = StandardScaler().fit_transform(X_1)
standardized_data

array([[-1.26113654,  1.0789687 ],
       [-0.69265848, -0.58621605],
       [ 1.07961403,  0.84237863],
       [ 0.87418099, -1.33513128]])

In [160]:
# standard deviation
def st_dev (ser):
    n = len(X_1)
    mean = ser.sum()/n
    sq_diff = ((ser - mean)**2).sum()
    return (sq_diff/(n-1))**.5

In [161]:
print(st_dev(X_1))

1.9500787498486474
